# Generated by Django 5.2.8 on 2025-12-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('teams', '0002_alter_workspace_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='teams.workspace'),
        ),
    ]
