# Generated by Django 5.2.8 on 2025-12-15 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='subteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='teams.subteam'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('WORKSPACE', 'Workspace'), ('SUBTEAM', 'Sub-team')], default='PRIVATE', max_length=10),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='teams.workspace'),
        ),
    ]
